title = "Gaussian Sheep"
baseURL = "http://gaussian-sheep.netlify.com"
languageCode = "en-us"
theme = "gohugo-theme-ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-109825853-1"
enableRobotsTXT = true
disqusShortname = "gaussian-sheep"

[sitemap]
  changefreq = "daily"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "/images/gsfavicon.jpg"
  description = "Let Blog(x) s.t. Blog : My Mind => The Interwebs"
  facebook = ""
  twitter = "http://twitter.com/GaussianSheep"
  instagram = ""
  youtube = ""
  github = ""
  linkedin = "https://linkedin.com/in/cammyoung"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/allanandcamtree.jpg"
  recent_posts_number = 5
